### PR TITLE
support lexer directives in input files

### PR DESCRIPTION
**Pull request by gasche**
In Batteries it would be helpful to have qtest recognize lexer directives in input files (it gives compilation errors in the right place for test that comes from preprocessed `.mlv` files).

### CODE REVIEW

**Comment by c-cube** [comment]
So, this makes `#line foo` and the likes parsed properly? Good idea, thanks. Would it also work for, say, `cppo`?

**Comment by gasche** [comment]
I updated the PR with a `cppo` test. It works just fine.

**Comment by c-cube** [comment]
Very nice, thanks. Would you want me to release quickly?

**Comment by gasche** [comment]
Do as is convenient for you for the release -- it will be a nice ergonomic improvement, but it's not blocking anything Batteries-wise.

**Pull request merged**
